### ISSUE TITLE
Understanding the terrain munge

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#80]
I was taking it out for a spin just now but there hasn't been much success. Maybe it's something I've misunderstood, but then again the error message I get leaves practically everything up for imagination.

`Error munging RhenVar1.tmtrl: The request is not supported.`

Essentially the terrain doesn't get munged at all. I pretty much copied the config file from the example but I'll stamp it here just in case I screwed it up.

```
Global:
   UseEnvironmentMapping: no
   
   UseZEStaticLighting: yes
   
   sRGBDiffuseMaps: yes
   
   BumpMappingType: Normal Mapping

   Rendertype: normal_ext

   DiffuseColor: [1.0, 1.0, 1.0]
   SpecularColor: [1.0, 1.0, 1.0]

Materials:
   Rhn1_far:
      DiffuseMap: Rhn1_far_diffuse
      NormalMap: Rhn1_far_normal
      GlossMap: Rhn1_far_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0

   Rhn1_main_2:
      DiffuseMap: Rhn1_main_2_diffuse
      NormalMap: Rhn1_main_2_normal
      GlossMap: Rhn1_main_2_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0

   Rhn1_main_2a:
      DiffuseMap: Rhn1_main_2a_diffuse
      NormalMap: Rhn1_main_2a_normal
      GlossMap: Rhn1_main_2a_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0

   Rhn1_main_4:
      DiffuseMap: Rhn1_main_4_diffuse
      NormalMap: Rhn1_main_4_normal
      GlossMap: Rhn1_main_4_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0

   Rhn1_main_5:
      DiffuseMap: Rhn1_main_5_diffuse
      NormalMap: Rhn1_main_5_normal
      GlossMap: Rhn1_main_5_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0

   Rhn1_main_8:
      DiffuseMap: Rhn1_main_8_diffuse
      NormalMap: Rhn1_main_8_normal
      GlossMap: Rhn1_main_8_specular
      AOMap: $null_ao
      HeightMap: $null_heightmap
      HeightScale: 0.05
      SpecularExponent: 128.0
```

So there are a few things I need clarified as well. I noticed that gloss maps for terrain are now separate from the normal map in the case of normal_ext, what sort of format does it expect for it? Is BC4 sufficient for it?

Also I was curious about the whole environment mapping thing. It doesn't actually have anything to do with this, but do we have any way to actually create cube textures?

Furthermore, just so this isn't mere idle questioning there was a minor inconvenience I came across. If the terrain material file has any extra notes commented out with #, it causes an error and fails the munge.
